# Site settings
name: Irfan Test
title: Irfan Test
description: The ultimate website where you can download official ROMs and firmware packages for Xiaomi devices!
keywords: xiaomi, xiaomi firmware, xiaomi firmware updater, firmware updater, firmware download, firmware, firmware downloader, firmware update, xiaomi firmware download, xiaomi firmware update, Xiaomi update, XDA, Xiaomi XDA, Firmware XDA, yshalsager, xfu, redmi, mi, pocophone, poco, irfan test
url: https://irfan-test.com
permalink: /:categories/:title/
repository: irfaaan/irfaaan.github.io
author: irfan
email: loffer@haren.uk

plugins:
  - jekyll-feed
  - jekyll-sitemap

members:
  - berkantkz
  - yshalsager

exclude:
  - data_generator/
